language: go
go:
  - 1.12.x
install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
script:
  - go test ./raingutter -v
  - docker run --rm -i hadolint/hadolint < Dockerfile
group: stable
dist: trusty
os: linux
branches:
  only: master
