apiVersion: skaffold/v1beta15
kind: Config
build:
  artifacts:
  - image: zendesk/raingutter
    docker:
      dockerfile: Dockerfile
      buildArgs:
        version: "161"
  - image: zendesk/mock-raindrops
    context: ./misc/
    docker:
      dockerfile: Dockerfile-raindrops.ms
  - image: zendesk/mock-dogstatsd
    context: ./misc/
    docker:
      dockerfile: Dockerfile-dogstatsd.ms
deploy:
  kubectl:
    manifests:
    - kubernetes/deployment.yml
