---
apiVersion: skaffold/v2beta23
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: raingutter
      docker:
        dockerfile: Dockerfile
        buildArgs:
          version: "161"
    - image: mock-raindrops
      context: ./misc/raindrops/
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - kubernetes/unicorn-raindrops.yml
      - kubernetes/unicorn-socket-stats.yml
      - kubernetes/puma-socket-stats.yml
