---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rg
  namespace: unicorn-raindrops
spec:
  selector:
    matchLabels:
      app: rg
  replicas: 1
  template:
    metadata:
      labels:
        app: rg
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8000'
    spec:
      containers:
        - name: raingutter
          image: raingutter
          env:
            - name: RG_UNICORN_PORT
              value: '3000'
            - name: RG_USE_SOCKET_STATS
              value: 'false'
            - name: RG_RAINDROPS_URL
              value: 'http://127.0.0.1:3000/_raindrops'
            - name: RG_STATSD_NAMESPACE
              value: 'raingutter.unicorn-raindrops.dev.'
            - name: UNICORN_WORKERS
              value: '16'
            - name: RG_STATSD_HOST
              value: '127.0.0.1'
            - name: RG_STATSD_PORT
              value: '8125'
            - name: POD_NAME
              value: 'myapp-app-server'
            - name: POD_NAMESPACE
              value: 'unicorn-raindrops'
            - name: PROJECT
              value: 'my-project'
            - name: RG_PROMETHEUS_ENABLED
              value: 'true'
            - name: RG_FREQUENCY
              value: '5000'
            - name: RG_STATSD_EXTRA_TAGS
              value: 'extratag1:1,extratag2:2'
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
          imagePullPolicy: IfNotPresent
        - name: statsd-logger
          image: zendesk/statsd-logger
          imagePullPolicy: IfNotPresent
        - name: mock-raindrops
          image: mock-raindrops
          imagePullPolicy: IfNotPresent
      terminationGracePeriodSeconds: 1
      restartPolicy: Always
      dnsPolicy: ClusterFirst
