name: repo-checks
on:
  push:
    branches:
    - master
  pull_request:

env:
  AWS_PROFILE: ecr-publish

jobs:
  main:
    name: go-lang
    runs-on: ubuntu-latest
    env:
      APP_ENV: test
      GOPATH: ${{ github.workspace }}/gopath
      GOPRIVATE: github.com/zendesk/*
    steps:
    - uses: zendesk/checkout@v3
      with:
        path: ${{ github.workspace }}/gopath/src/github.com/zendesk/${{ github.repository }}
    - uses: zendesk/setup-go@v2
      with:
        go-version: 1.17.x
    - name: go test
      run: |
        unset GOPROXY
        git config --global url."https://${{ secrets.ORG_GITHUB_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
        cd ${{ github.workspace }}/gopath/src/github.com/zendesk/${{ github.repository }}
        go test ./raingutter -v
        docker run --rm -i gcr.io/docker-images-180022/dockerhub-mirror/hadolint/hadolint < Dockerfile

