name: repo-checks
on:
  push:
    branches:
    - master
  pull_request:
jobs:
  main:
    name: go-lang
    runs-on: [self-hosted, zendesk-stable]
    env:
      APP_ENV: test
    steps:
    - uses: zendesk/checkout@v2
    - uses: zendesk/setup-go@v2
      with:
        go-version: 1.12.x
    - name: go test
      run: |
        unset GOPROXY
        git config --global url."https://${{ secrets.ORG_GITHUB_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
        go get -u github.com/golang/dep/cmd/dep
        dep ensure
        go test ./raingutter -v
        docker run --rm -i hadolint/hadolint < Dockerfile

