name: Github Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  github_release:
    runs-on: ubuntu-latest 
    steps:
      # Check out the `master` branch
      - uses: zendesk/checkout@v4
      # Compute the next semantic version.
      - name: Compute release tag
        id: compute_tag
        uses: zendesk/compute-tag@v18
        with:
          github_token: ${{ github.token }}
          version_scheme: semantic
      # Create a new GitHub release
      - name: Create release
        id: create_release
        uses: zendesk/create-release@v1.1.4
        with:
          tag_name: ${{ steps.compute_tag.outputs.next_tag }}
          release_name: ${{ steps.compute_tag.outputs.next_tag }}
          commitish: ${{ github.git_ref }}
          body: |
            ### Links
            See the full [CHANGELOG](https://github.com/${{ github.repository }}/tree/master/CHANGELOG.md)
            for full release details.

            * [Changes since last release](https://github.com/${{ github.repository }}/compare/${{ steps.compute_tag.outputs.previous_tag }}..${{ steps.compute_tag.outputs.next_tag }})
        env:
          GITHUB_TOKEN: ${{ github.token }}

